//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Barcodes = new HashSet<Barcode>();
        }
    
        public int Book_ID { get; set; }
        public string BName { get; set; }
        public decimal Price { get; set; }
        public int Author_ID { get; set; }
        public int Publisher_ID { get; set; }
        public int MainCategory_ID { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Barcode> Barcodes { get; set; }
        public virtual MainCategory MainCategory { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
