//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowDetail
    {
        public int BorrowDetail_ID { get; set; }
        public int BorrowHeader_ID { get; set; }
        public int Barcode_ID { get; set; }
        public int Status_ID { get; set; }
    
        public virtual Barcode Barcode { get; set; }
        public virtual BorrowHeader BorrowHeader { get; set; }
        public virtual Status Status { get; set; }
    }
}
