//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Login_ID { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public int Emp_ID { get; set; }
        public int Status_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Status Status { get; set; }
    }
}
