//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int Penalty_ID { get; set; }
        public int LateDays { get; set; }
        public decimal Penalty_Amount { get; set; }
        public int BorrowHeader_ID { get; set; }
    
        public virtual BorrowHeader BorrowHeader { get; set; }
    }
}
