//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register_fee
    {
        public int Register_fee_ID { get; set; }
        public System.DateTime Register_Date { get; set; }
        public decimal Register_fee1 { get; set; }
        public int User_ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
