//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public int SubCategory_ID { get; set; }
        public string SubCategory1 { get; set; }
        public int MainCategory_ID { get; set; }
    
        public virtual MainCategory MainCategory { get; set; }
    }
}
