//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.BorrowHeaders = new HashSet<BorrowHeader>();
            this.Register_fee = new HashSet<Register_fee>();
        }
    
        public int User_ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Tel_Land { get; set; }
        public string Tel_Hand { get; set; }
        public System.DateTime DOB { get; set; }
        public string Email { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public int User_Type_ID { get; set; }
        public int Refree_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowHeader> BorrowHeaders { get; set; }
        public virtual Refree Refree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register_fee> Register_fee { get; set; }
        public virtual User_Type User_Type { get; set; }
    }
}
