<?xml version="1.0" encoding="utf-8"?><Database Name="LibraryDB" Class="DB_ClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=legendsy.database.windows.net;Initial Catalog=LibraryDB;Persist Security Info=True;User ID=testAddmin" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="LibraryDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.User_Type" Member="User_Types">
    <Type Name="User_Type">
      <Column Name="User_Type_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_Type" Member="User_Type1" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="User_Type_User" Member="Users" ThisKey="User_Type_ID" OtherKey="User_Type_ID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Author" Member="Authors">
    <Type Name="Author">
      <Column Name="Author_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Author" Member="Author1" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="Author_Book" Member="Books" ThisKey="Author_ID" OtherKey="Author_ID" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Barcode" Member="Barcodes">
    <Type Name="Barcode">
      <Column Name="Barcode_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Barcode" Member="Barcode1" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Book_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Barcode_BorrowDetail" Member="BorrowDetails" ThisKey="Barcode_ID" OtherKey="Barcode_ID" Type="BorrowDetail" />
      <Association Name="Book_Barcode" Member="Book" ThisKey="Book_ID" OtherKey="Book_ID" Type="Book" IsForeignKey="true" />
      <Association Name="Status_Barcode" Member="Status" ThisKey="Status_ID" OtherKey="Status_ID" Type="Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="Book_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="Author_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Publisher_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MainCategory_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Book_Barcode" Member="Barcodes" ThisKey="Book_ID" OtherKey="Book_ID" Type="Barcode" />
      <Association Name="Author_Book" Member="Author" ThisKey="Author_ID" OtherKey="Author_ID" Type="Author" IsForeignKey="true" />
      <Association Name="MainCategory_Book" Member="MainCategory" ThisKey="MainCategory_ID" OtherKey="MainCategory_ID" Type="MainCategory" IsForeignKey="true" />
      <Association Name="Publisher_Book" Member="Publisher" ThisKey="Publisher_ID" OtherKey="Publisher_ID" Type="Publisher" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BorrowDetail" Member="BorrowDetails">
    <Type Name="BorrowDetail">
      <Column Name="BorrowDetail_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BorrowHeader_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Barcode_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Barcode_BorrowDetail" Member="Barcode" ThisKey="Barcode_ID" OtherKey="Barcode_ID" Type="Barcode" IsForeignKey="true" />
      <Association Name="BorrowHeader_BorrowDetail" Member="BorrowHeader" ThisKey="BorrowHeader_ID" OtherKey="BorrowHeader_ID" Type="BorrowHeader" IsForeignKey="true" />
      <Association Name="Status_BorrowDetail" Member="Status" ThisKey="Status_ID" OtherKey="Status_ID" Type="Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BorrowHeader" Member="BorrowHeaders">
    <Type Name="BorrowHeader">
      <Column Name="BorrowHeader_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Borrow_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BorrowHeader_BorrowDetail" Member="BorrowDetails" ThisKey="BorrowHeader_ID" OtherKey="BorrowHeader_ID" Type="BorrowDetail" />
      <Association Name="BorrowHeader_Penalty" Member="Penalties" ThisKey="BorrowHeader_ID" OtherKey="BorrowHeader_ID" Type="Penalty" />
      <Association Name="User_BorrowHeader" Member="User" ThisKey="User_ID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="Emp_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Emp_NIC" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="FName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Add1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Add2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Add3" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Employee_Login" Member="Loginzs" Storage="_Logins" ThisKey="Emp_ID" OtherKey="Emp_ID" Type="Loginz" />
    </Type>
  </Table>
  <Table Name="dbo.Fee" Member="Fees">
    <Type Name="Fee">
      <Column Name="Fee_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Register_fee" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Penalty_fee" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Login" Member="Loginzs">
    <Type Name="Loginz">
      <Column Name="Login_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pwd" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Emp_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="User_Type_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Login" Member="Employee" ThisKey="Emp_ID" OtherKey="Emp_ID" Type="Employee" IsForeignKey="true" />
      <Association Name="Status_Login" Member="Status" ThisKey="Status_ID" OtherKey="Status_ID" Type="Status" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MainCategory" Member="MainCategories">
    <Type Name="MainCategory">
      <Column Name="MainCategory_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MainCategory" Member="MainCategory1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="MainCategory_Book" Member="Books" ThisKey="MainCategory_ID" OtherKey="MainCategory_ID" Type="Book" />
      <Association Name="MainCategory_SubCategory" Member="SubCategories" ThisKey="MainCategory_ID" OtherKey="MainCategory_ID" Type="SubCategory" />
    </Type>
  </Table>
  <Table Name="dbo.Penalty" Member="Penalties">
    <Type Name="Penalty">
      <Column Name="Penalty_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LateDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Penalty_Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BorrowHeader_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BorrowHeader_Penalty" Member="BorrowHeader" ThisKey="BorrowHeader_ID" OtherKey="BorrowHeader_ID" Type="BorrowHeader" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Publisher" Member="Publishers">
    <Type Name="Publisher">
      <Column Name="Publisher_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Publisher" Member="Publisher1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Add1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Add2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Add3" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Publisher_Book" Member="Books" ThisKey="Publisher_ID" OtherKey="Publisher_ID" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Refree" Member="Refrees">
    <Type Name="Refree">
      <Column Name="Refree_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Add1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Add2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Add3" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Refree_User" Member="Users" ThisKey="Refree_ID" OtherKey="Refree_ID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Register_fee" Member="Register_fees">
    <Type Name="Register_fee">
      <Column Name="Register_fee_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Register_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Register_fee" Member="Register_fee1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Register_fee" Member="User" ThisKey="User_ID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="Status_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Member="Status1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Status_Barcode" Member="Barcodes" ThisKey="Status_ID" OtherKey="Status_ID" Type="Barcode" />
      <Association Name="Status_BorrowDetail" Member="BorrowDetails" ThisKey="Status_ID" OtherKey="Status_ID" Type="BorrowDetail" />
      <Association Name="Status_Login" Member="Loginzs" Storage="_Logins" ThisKey="Status_ID" OtherKey="Status_ID" Type="Loginz" />
    </Type>
  </Table>
  <Table Name="dbo.SubCategory" Member="SubCategories">
    <Type Name="SubCategory">
      <Column Name="SubCategory_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubCategory" Member="SubCategory1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MainCategory_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MainCategory_SubCategory" Member="MainCategory" ThisKey="MainCategory_ID" OtherKey="MainCategory_ID" Type="MainCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sysdiagrams" Member="sysdiagrams">
    <Type Name="sysdiagram">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="diagram_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="definition" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Tel_Land" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Tel_Hand" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Add1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Add2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Add3" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="User_Type_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Refree_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_BorrowHeader" Member="BorrowHeaders" ThisKey="User_ID" OtherKey="User_ID" Type="BorrowHeader" />
      <Association Name="User_Register_fee" Member="Register_fees" ThisKey="User_ID" OtherKey="User_ID" Type="Register_fee" />
      <Association Name="Refree_User" Member="Refree" ThisKey="Refree_ID" OtherKey="Refree_ID" Type="Refree" IsForeignKey="true" />
      <Association Name="User_Type_User" Member="User_Type" ThisKey="User_Type_ID" OtherKey="User_Type_ID" Type="User_Type" IsForeignKey="true" />
    </Type>
  </Table>
</Database>